Migrate fields and records to a new module
StefanRijnhart/community-data-files pull request #1
Opened 2021-12-07 11:19 UTC by mmequignon

Some fields and models aren't ported from 13.0 to 14.0.
A new module introduced here https://github.com/OCA/community-data-files/pull/118
adds those fields and records, but we need a migration script as well.

2021-12-07 11:34 UTC, sebalix commented on l10n_eu_product_adr/migrations/14.0.1.1.0/pre-dangerous-goods.py
> +MODULE_NAMES_TO_MOVE = (
```suggestion
MODELS_TO_MOVE = (
```

2021-12-07 11:34 UTC, sebalix commented on l10n_eu_product_adr/migrations/14.0.1.1.0/pre-dangerous-goods.py
> +    cr.execute(QUERY_GET_NAMES, (PREVIOUS_MODULE_NAME, MODULE_NAMES_TO_MOVE))
```suggestion
    cr.execute(QUERY_GET_NAMES, (PREVIOUS_MODULE_NAME, MODELS_TO_MOVE))
```

2021-12-07 13:19 UTC, sebalix requested changes
The path of the migration script should be `migrations/14.0.1.0.0`, it's not a migration related to `14.0.1.1.0` specifically.

2021-12-07 13:52 UTC, sebalix commented on l10n_eu_product_adr/migrations/14.0.1.1.0/pre-dangerous-goods.py
> +        "limited_quantity",
This field doesn't exist on 13.0, to remove, it makes the script crashing at some point.
```suggestion
```

2021-12-08 06:05 UTC, TDu approved these changes

2021-12-08 08:56 UTC, sebalix reviewed
A warning for the 13.0 users in the addon description is welcome to tell that dangerous goods attributes have been migrated to `l10n_eu_product_adr_dangerous_goods` and that they should install this addon themself to get their data back.

2021-12-23 14:06 UTC, sebalix commented
I can not edit the description, but this PR aims to improve the state of https://github.com/OCA/community-data-files/pull/109.

2022-08-29 11:39 UTC, closed without merging